### PR TITLE
Add BPFd source files to BCC source tree

### PR DESCRIPTION
**Pull request by jcanseco**
This adds the source files for BPFd from commit
5db1d84c922be6c1e3aeb5e40253b2f478907f05 of the original BPFd repository
(https://github.com/joelagnel/bpfd).

This is so that BPFd can be built together with BCC.

Signed-off-by: Jazel Canseco <jcanseco@google.com>

### CODE REVIEW

**Review by joelagnel — COMMENTED** [review]
This looks good as a first pass.

Could you moved bpfd to its own directory? Sorry I should have told you to do that from the beginning.

Also write a sync.sh shell script that does the following:
- clone bpfd,
- update the sources
- delete the clone.

Then check in this script into the both bpfd and the bpfd copy. thanks!

**Comment by joelagnel** [comment]
Just to clarify, the script should sync bpfd sources from upstream bpfd. It will make it so much easier for us to update bpfd in the future.

**Comment by jcanseco** [comment]
Okay, I'll put the BPFd source files into its own directory.

To be sure, is the sync.sh script just a temporary solution? I find that it might be best in the long term if we do all BPFd development straight in the BCC source tree, since keeping them separate would require us having to keep two separate copies of the BPFd source in sync. To be clear, I think it's fine as a temporary solution, but such a script would likely not be feasible in the long-run as the BPFd source tree evolves.

**Comment by joelagnel** [comment]
The "copy" is just for testing, not for development. For development, BPFd from outside BCC should be used. The sync script can even be made to run during the test itself  (sync the sources before building BPFd).
So don't worry about the sources going out of sync, we only work from one copy.

**Comment by jcanseco** [comment]
I placed BPFd sources into its own directory.

Also, I'll write the sync.sh script in a separate branch and make a PR for it later if that's okay.

**Pull request merged**
